In [18]:
import gym
import random
import time
import numpy as np
from IPython.display import clear_output
env = gym.make("FrozenLake-v0").env
env.render()


SFFF
FHFH
FFFH
HFFG


In [19]:
action_space_size = env.action_space.n
state_space_size = env.observation_space.n
print(action_space_size)
print(state_space_size)

4
16


In [20]:
q_table = np.zeros((state_space_size, action_space_size)) #16 by 4
print(q_table)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [27]:
epochs = 10000
max_steps = 50

learning_rate = 0.2
discount_rate = 0.7

exploration_rate = 1
max_exploration_rate = 1
min_exploration_rate = 0.01
exploration_decay_rate = 0.02

In [28]:
rewards_all = []

for episode in range(epochs):
    state = env.reset()
    done = False
    current_reward = 0
    for step in range(max_steps):
        exploration_rate_threshold = random.uniform(0,1)
        if exploration_rate_threshold > exploration_rate:
            action = np.argmax(q_table[state,:])
        else:
            action = env.action_space.sample()
            
        new_state, reward, done, info = env.step(action)
        
        q_table[state, action] = q_table[state, action] * (1 - learning_rate) + learning_rate*(reward  + discount_rate * np.max(q_table[new_state,:])) 
        
        state = new_state
        current_reward += reward
        
        if done == True:
            break
        
    exploration_rate = min_exploration_rate + (max_exploration_rate - min_exploration_rate) * np.exp(-exploration_decay_rate*episode)
    
    rewards_all.append(current_reward)
    
rewards_print = np.split(np.array(rewards_all), epochs/1000)
    
count = 1000
print("*******Average reward per thousand episodes******\n")
for r in rewards_print:
    print(count, ": ", str(sum(r/1000)))
    count += 1000
        
    #print("\n\n*******Q-table******\n")
    #print(q_table)

*******Average reward per thousand episodes******

1000 :  0.21600000000000016
2000 :  0.19900000000000015
3000 :  0.1440000000000001
4000 :  0.2730000000000002
5000 :  0.20300000000000015
6000 :  0.11200000000000009
7000 :  0.09000000000000007
8000 :  0.09100000000000007
9000 :  0.1370000000000001
10000 :  0.10900000000000008
