In [54]:
import gym
import random
import time
import numpy as np
from IPython.display import clear_output
env = gym.make("FrozenLake-v0").env
env.render()


SFFF
FHFH
FFFH
HFFG


In [55]:
action_space_size = env.action_space.n
state_space_size = env.observation_space.n
print(action_space_size)
print(state_space_size)

4
16


In [56]:
q_table = np.zeros((state_space_size, action_space_size)) #16 by 4
print(q_table)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [57]:
epochs = 10000
max_steps = 100

learning_rate = 0.1
discount_rate = 0.6

exploration_rate = 1
max_exploration_rate = 1
min_exploration_rate = 0.01
exploration_decay_rate = 0.001

In [60]:
rewards_all = []
for episode in range(epochs):
    state = env.reset()
    done = False
    current_reward = 0
    for step in range(max_steps):
        exploration_rate_threshold = random.uniform(0,1)
        if exploration_rate_threshold > exploration_rate:
            action = np.argmax(q_table[state,:])
        else:
            action = env.action_space.sample()
        new_state, reward, done, info = env.step(action)
        q_table[state, action] = q_table[state, action] * (1 - learning_rate) + learning_rate*(reward  + discount_rate * np.max(q_table[new_state,:])) 
        
        state = new_state
        current_reward += reward
        if done == True:
            break
        
        eploration_rate = min_exploration_rate + (max_exploration_rate - min_exploration_rate) * np.exp(-exploration_decay_rate*episode)
        rewards_all.append(current_reward)
    rewards_print = np.split(np.array(rewards_all), epochs/1000)
    count = 1000
    print("*******Average reward per thousand episodes******\n")
    for r in rewards_print:
        print(count, ": ", str(sum(r/1000)))
        count += 1000
    print("\n\n*******Q-table******\n")
    print(q_table)

*******Average reward per thousand episodes******

1000 :  0.0
2000 :  0.0
3000 :  0.0
4000 :  0.0
5000 :  0.0
6000 :  0.0
7000 :  0.0
8000 :  0.0
9000 :  0.0
10000 :  0.0


*******Q-table******\m
[[0.00187644 0.00222504 0.00201992 0.00157547]
 [0.00121217 0.00319991 0.00236239 0.00305208]
 [0.01049425 0.00587251 0.00850335 0.00335678]
 [0.00281885 0.00245708 0.00201835 0.00444999]
 [0.00517639 0.00495613 0.00338762 0.00164359]
 [0.         0.         0.         0.        ]
 [0.04178546 0.01426083 0.02949371 0.00096042]
 [0.         0.         0.         0.        ]
 [0.00442574 0.01091717 0.0099489  0.01590607]
 [0.0212263  0.0597855  0.0476525  0.02988644]
 [0.10949094 0.12988196 0.09035403 0.0148735 ]
 [0.         0.         0.         0.        ]
 [0.         0.         0.         0.        ]
 [0.02199922 0.11361389 0.08276913 0.05623987]
 [0.1237882  0.45963654 0.31005817 0.27248813]
 [0.         0.         0.         0.        ]]


ValueError: array split does not result in an equal division