In [179]:
import gym
import random
import time
import numpy as np
from IPython.display import clear_output
env = gym.make("FrozenLake-v0").env
env.render()


SFFF
FHFH
FFFH
HFFG


In [180]:
action_space_size = env.action_space.n
state_space_size = env.observation_space.n
print(action_space_size)
print(state_space_size)

4
16


In [181]:
q_table = np.zeros((state_space_size, action_space_size)) #16 by 4
print(q_table)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [187]:
epochs = 10000
max_steps = 100

learning_rate = 0.1
discount_rate = 0.99

exploration_rate = 1
max_exploration_rate = 1
min_exploration_rate = 0.01
exploration_decay_rate = 0.01

In [188]:
rewards_all = []

for episode in range(epochs):
    state = env.reset()
    done = False
    current_reward = 0
    for step in range(max_steps):
        exploration_rate_threshold = random.uniform(0,1)
        if exploration_rate_threshold > exploration_rate:
            action = np.argmax(q_table[state,:])
        else:
            action = env.action_space.sample()
            
        new_state, reward, done, info = env.step(action)
        
        q_table[state, action] = q_table[state, action] * (1 - learning_rate) + learning_rate*(reward  + discount_rate * np.max(q_table[new_state,:])) 
        
        state = new_state
        current_reward += reward
        
        if done == True:
            break
        
    exploration_rate = min_exploration_rate + (max_exploration_rate - min_exploration_rate) * np.exp(-exploration_decay_rate*episode)
    
    rewards_all.append(current_reward)
    
rewards_print = np.split(np.array(rewards_all), epochs/1000)
#env.render()

accuracy = []
for r in rewards_print:
    accuracy.append(sum(r/1000))

In [189]:
count = 1000
print("*******Average accuracy per thousand episodes******\n")
for i in accuracy:
    print(count, ": ", i)
    count += 1000

*******Average accuracy per thousand episodes******

1000 :  0.22200000000000017
2000 :  0.3050000000000002
3000 :  0.33100000000000024
4000 :  0.5010000000000003
5000 :  0.6480000000000005
6000 :  0.6730000000000005
7000 :  0.6710000000000005
8000 :  0.6380000000000005
9000 :  0.6750000000000005
10000 :  0.7010000000000005


In [192]:
print("max:", np.amax(accuracy), "at:", 1+np.argmax(accuracy, axis=0))

max: 0.7010000000000005 at: 10


In [191]:
for episodes in range(3):
    state = env.reset()
    done = False
    
    print("EPISODE:", episode + 1, "**********\n\n\n")
    time.sleep(1)
    for step in range(max_steps):
        clear_output(wait = True)
        env.render()
        time.sleep(0.3)
        action = np.argmax(q_table[state,:])
        new_state,reward,done, info = env.step(action)
        if done:
            clear_output(wait = True)
            env.render()
            time.sleep(0.3)
            if reward == 1:
                print("******YOU WIN!!!******")
                time.sleep(1)
            else:
                print("******YOU LOSE!!!******")
                time.sleep(1)
            clear_output(wait = True)
            break
    state = new_state
env.close()

        

  (Left)
SFFF
FHFH
FFFH
HFFG
******YOU LOSE!!!******
